In [1]:
import stim

In [2]:
circuit = stim.Circuit("""
    H 0
    TICK

    CX 0 1
    X_ERROR(0.2) 0 1
    TICK

    M 0 1
    DETECTOR rec[-1] rec[-2]
""")

In [22]:
for c in circuit:
    # print(c)
    print(c.name, c.target_groups())

H [[stim.GateTarget(0)]]
TICK []
CX [[stim.GateTarget(0), stim.GateTarget(1)]]
X_ERROR [[stim.GateTarget(0)], [stim.GateTarget(1)]]
TICK []
M [[stim.GateTarget(0)], [stim.GateTarget(1)]]
DETECTOR [[stim.target_rec(-1)], [stim.target_rec(-2)]]


In [7]:
import numpy as np

v = 4
np.packbits(
    np.array(list(np.binary_repr(v)), dtype=np.uint8),
    bitorder="little",
)

['1', '0', '0']


array([1], dtype=uint8)

In [24]:
np.packbits([0,0,0,0,0,0,0,0,0,0,0,0,0,1,0], bitorder="little")

array([ 0, 32], dtype=uint8)

In [30]:
np.packbits([0,0,1,0,0,0,0,0,0,0,0,0], bitorder="little")

array([4, 0], dtype=uint8)

In [35]:
np.array(list(np.binary_repr(4, width=16))[::-1], dtype=np.uint8),

(array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),)

In [37]:
np.packbits(np.array(list(np.binary_repr(4, width=32))[::-1], dtype=np.uint8), bitorder="little")

array([4, 0, 0, 0], dtype=uint8)

In [38]:
np.packbits(4, bitorder="little")

array([1], dtype=uint8)

In [39]:
np.binary_repr(v)

'100'